# Generated by Django 5.0.3 on 2025-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='categoria',
            field=models.CharField(default='ansiedad', max_length=200),
            preserve_default=False,
        ),
    ]
