# Generated by Django 5.1.5 on 2025-02-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_estudiante', to='dashboard.estudiante', verbose_name='Estudiante'),
        ),
    ]
