# Generated by Django 5.1.5 on 2025-02-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_cita_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('deseo', models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('peticion', 'Petición')], max_length=10, verbose_name='Tipo de solicitud')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
