# Generated by Django 5.0.3 on 2025-03-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_contacto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='deseo',
            field=models.CharField(choices=[('queja', 'Queja'), ('reclamo', 'Reclamo'), ('peticion', 'Petición')], default='peticion', max_length=10, verbose_name='Tipo de solicitud'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('tarjeta_identidad', 'Tarjeta de Identidad')], default='cedula', max_length=20, null=True),
        ),
    ]
