# Generated by Django 4.0.3 on 2025-01-28 16:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0004_alter_usuariopersonalizado_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'Usuario Personalizado', 'verbose_name_plural': 'Usuarios Personalizados'},
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='alergias',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='curso',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='enfermedades',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True, verbose_name='Enfermedades'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='eps',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='imagen',
            field=models.ImageField(blank=True, default='images/users/user-4.jpg', null=True, upload_to='emedia/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('psicologo', 'Psicólogo'), ('administrativo', 'Administrativo')], default='estudiante', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
