# Generated by Django 5.0.3 on 2025-03-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_contacto_deseo_alter_horario_dia_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia_semana',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('tarjeta_identidad', 'Tarjeta de Identidad')], max_length=20, null=True),
        ),
    ]
