# Generated by Django 4.0.3 on 2025-01-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0005_alter_usuariopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='alergias',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='curso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='enfermedades',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='eps',
            field=models.CharField(blank=True, default='Ninguna', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='imagen',
            field=models.ImageField(blank=True, default='images/users/user-4.jpg', null=True, upload_to='emedia/'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('psicologo', 'Psicólogo'), ('administrativo', 'Administrativo')], default='estudiante', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='usuario_personalizado_set', to='auth.permission'),
        ),
    ]
