# Generated by Django 4.0.3 on 2025-01-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0006_alter_usuariopersonalizado_alergias_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_personalizado_groups', related_query_name='usuario_personalizado', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_personalizado_user_permissions', related_query_name='usuario_personalizado', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especializacion', models.CharField(blank=True, max_length=200, null=True)),
                ('horarios_disponibles', models.TextField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo', to='dashboard.usuariopersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(blank=True, max_length=200, null=True)),
                ('alergias', models.CharField(blank=True, max_length=200, null=True)),
                ('enfermedades', models.CharField(blank=True, max_length=200, null=True)),
                ('curso', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='emedia/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='dashboard.usuariopersonalizado')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrativo', to='dashboard.usuariopersonalizado')),
            ],
        ),
    ]
