# Generated by Django 5.0.3 on 2025-03-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
    ]
