# Generated by Django 4.0.3 on 2025-01-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_usuariopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='identificacion',
            field=models.CharField(default='1', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('cedula', 'Cédula'), ('tarjeta_identidad', 'Tarjeta de Identidad')], max_length=20, null=True),
        ),
    ]
