# Generated by Django 4.0.3 on 2025-01-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_usuariopersonalizado_identificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='emedia/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='alergias',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='enfermedades',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='eps',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
    ]
