# Generated by Django 5.1.6 on 2025-03-20 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_respuesta_pregunta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.cita')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.estudiante')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.psicologo')),
            ],
        ),
    ]
