# Generated by Django 5.0.3 on 2025-03-23 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contacto', 'Nuevo mensaje de contacto'), ('cita', 'Nueva cita agendada'), ('sistema', 'Actualización del sistema'), ('recordatorio', 'Recordatorio de cita')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
