# Generated by Django 4.0.3 on 2025-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_estudiante_curso_remove_estudiante_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='enfermedades',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='eps',
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='alergias',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='enfermedades',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='eps',
            field=models.CharField(blank=True, default='ninguna', max_length=200, null=True),
        ),
    ]
