# Generated by Django 5.0.3 on 2025-03-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario_tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('psicologo', 'Psicólogo'), ('administrativo', 'Administrativo'), ('todos', 'Todos los usuarios')], default='todos', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='relacionado_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.notificacion', verbose_name='Relacionado con'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('contacto', 'Nuevo mensaje'), ('cita', 'Actualización cita'), ('sistema', 'Actualización sistema')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
