# Generated by Django 5.1.5 on 2025-02-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_psicologo_horarios_disponibles_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='categoria',
            field=models.CharField(choices=[('ANS', 'Ansiedad'), ('EST', 'Estrés'), ('DIA', 'Diálogo'), ('AUT', 'Autoestima'), ('RES', 'Resiliencia'), ('EMP', 'Empatía')], default='ANS', max_length=3),
        ),
    ]
