# Generated by Django 5.0.3 on 2025-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_contacto_usuario_notificacion_destinatario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('contacto', 'Nuevo mensaje'), ('cita', 'Actualización cita'), ('sistema', 'Actualización sistema'), ('cuestionario', 'Cuestionario completado')], max_length=20),
        ),
    ]
