# Generated by Django 5.1.6 on 2025-04-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='destinatario_tipo',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('psicologo', 'Psicólogo'), ('todos', 'Todos los usuarios')], default='todos', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('psicologo', 'Psicólogo')], default='estudiante', max_length=20),
        ),
        migrations.DeleteModel(
            name='Administrativo',
        ),
    ]
