# Generated by Django 5.1.6 on 2025-04-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_notificacion_destinatario_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('psicologo', 'dia_semana')},
        ),
    ]
