# Generated by Django 5.1.6 on 2025-04-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_horario_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL amigable generada automáticamente desde el título', unique=True)),
                ('contenido', models.TextField(verbose_name='Contenido del Blog')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(choices=[('ansiedad', 'Ansiedad'), ('depresion', 'Depresión'), ('terapia', 'Terapia'), ('neurociencia', 'Neurociencia'), ('psicologia_positiva', 'Psicología Positiva'), ('desarrollo_personal', 'Desarrollo Personal'), ('otros', 'Otros')], default='otros', max_length=50)),
                ('publicado', models.BooleanField(default=False, help_text='Marcar para publicar el blog')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='dashboard.psicologo')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
