# Generated by Django 5.1.6 on 2025-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_blog_cita_destacada_alter_blog_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen Secundaria'),
        ),
    ]
