# Generated by Django 5.1.6 on 2025-05-30 03:49

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_blog_imagen_secundaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta_reporte', models.TextField(help_text='Detalle del motivo de la consulta tal como se registrará en el historial.', verbose_name='Motivo de Consulta (para el reporte)')),
                ('antecedentes_relevantes', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Información previa del estudiante que sea pertinente para el caso.', null=True, verbose_name='Antecedentes Relevantes')),
                ('evaluacion_sesion', ckeditor_uploader.fields.RichTextUploadingField(help_text='Descripción de lo ocurrido y evaluado durante la sesión.', verbose_name='Evaluación y Desarrollo de la Sesión')),
                ('diagnostico_impresion', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Análisis y conclusiones del psicólogo sobre el caso.', null=True, verbose_name='Impresión Diagnóstica / Conceptualización del Caso')),
                ('plan_intervencion_sugerencias', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Acciones a seguir, recomendaciones para el estudiante o terceros.', null=True, verbose_name='Plan de Intervención y Sugerencias')),
                ('evolucion_observaciones_adicionales', ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Progreso del estudiante y cualquier otra observación relevante.', null=True, verbose_name='Evolución y Observaciones Adicionales')),
                ('fecha_creacion_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación del Reporte')),
                ('ultima_actualizacion_reporte', models.DateTimeField(auto_now=True, verbose_name='Última Actualización del Reporte')),
                ('reporte_finalizado', models.BooleanField(default=False, help_text='Marcar si el psicólogo ha completado y revisado el reporte. Esto podría habilitar su descarga por el estudiante en el futuro.', verbose_name='Reporte Finalizado')),
                ('cita', models.OneToOneField(limit_choices_to={'estado': 'completada'}, on_delete=django.db.models.deletion.CASCADE, related_name='historial_clinico', to='dashboard.cita', verbose_name='Cita Asociada')),
            ],
            options={
                'verbose_name': 'Historial Clínico',
                'verbose_name_plural': 'Historiales Clínicos',
                'ordering': ['-cita__fecha_hora'],
            },
        ),
    ]
